version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exemplo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/IFSPhh2025@
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      neo4j:
        condition: service_started
    restart: always

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysql

volumes:
  mysql_data:
  neo4j_data: